"""Matrix Lie algebras over an algebra: ``su(n, A)`` and ``sl(n, A)``.

For an associative ``A`` the anti-Hermitian matrices close under the
commutator.  Over the octonions they do not, and the right objects are the
Lie algebras *generated* by the matrices acting as linear maps (Sudbery;
Barton and Sudbery, "Magic squares and matrix models of Lie algebras"; Dray
and Manogue)::

    import anyalgebra.composition as ca
    import anyalgebra.matrix_lie as ml

    print(ml.su(2, ca.octonions()).dimension)  # 36, the algebra so(9)
    print(ml.sl(2, ca.octonions()).dimension)  # 45, the algebra so(9,1)

Two actions are used.  A matrix acts on columns ``A^n`` by ``v -> M v``; this
serves ``n = 2`` for every algebra and any ``n`` for an associative one.  For
3-by-3 octonionic matrices the action is on the Hermitian matrices,
``X -> M X + X M^dagger``, which generates ``f4`` and ``e6``.  Other
combinations have no accepted definition and raise an error.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from fractions import Fraction

import anyalgebra.composition as ca
import anyalgebra.matrices as am
from anyalgebra.easy import Algebra, EasyError
from anyalgebra.lie import LieAlgebra, generated_by

Operator = tuple[tuple[Fraction, ...], ...]


def antihermitian_traceless(source: Algebra, size: int) -> tuple[am.Mat, ...]:
    """Return a basis of the anti-Hermitian matrices with trace zero.

    Its dimension is ``d n(n-1)/2 + (n-1)(d-1)`` for an algebra of
    dimension ``d``.
    """
    found = []
    imaginary = [x for x in source.basis if x != source.unit]
    for i in range(size - 1):
        for element in imaginary:
            found.append(
                am.unit(source, size, i, i, element)
                - am.unit(source, size, i + 1, i + 1, element)
            )
    found += [x for x in am.antihermitian_basis(source, size) if not x.trace()]
    return tuple(found)


def hermitian_traceless(source: Algebra, size: int) -> tuple[am.Mat, ...]:
    """Return a basis of the Hermitian matrices with trace zero."""
    found = [
        am.unit(source, size, i, i) - am.unit(source, size, i + 1, i + 1)
        for i in range(size - 1)
    ]
    found += [x for x in am.hermitian_basis(source, size) if not x.trace()]
    return tuple(found)


def column_action(matrix: am.Mat) -> Operator:
    """Return the rational matrix of ``v -> M v`` on columns ``A^n``."""
    source, size = matrix.algebra, matrix.rows
    columns = []
    for position in range(size):
        for element in source.basis:
            vector = am.matrix(
                source, [[element if row == position else 0] for row in range(size)]
            )
            columns.append(am.coordinates(matrix @ vector))
    return tuple(zip(*columns, strict=True))


def hermitian_action(matrix: am.Mat) -> Operator:
    """Return the rational matrix of ``X -> M X + X M^dagger`` on Hermitian matrices."""
    source, size = matrix.algebra, matrix.rows
    unit = source.unit_index
    if unit is None:
        raise EasyError("unit", f"{source.name} declares no unit")
    adjoint = matrix.dagger()
    columns = []
    for basis in am.hermitian_basis(source, size):
        image = matrix @ basis + basis @ adjoint
        vector = [image[i, i].vector[unit] for i in range(size)]
        for i in range(size):
            for j in range(i + 1, size):
                vector.extend(image[i, j].vector)
        columns.append(tuple(vector))
    return tuple(zip(*columns, strict=True))


def _operators(
    source: Algebra, size: int, generators: Sequence[am.Mat]
) -> list[Operator]:
    if size < 2:
        raise EasyError("shape", "the matrices must be at least 2-by-2")
    if size == 2 or ca.is_associative(source):
        return [column_action(matrix) for matrix in generators]
    if size == 3 and ca.is_alternative(source):
        return [hermitian_action(matrix) for matrix in generators]
    raise EasyError(
        "unsupported",
        f"no accepted definition for {size}-by-{size} matrices over {source.name}",
    )


def su(size: int, source: Algebra) -> LieAlgebra:
    """Return the Lie algebra generated by the traceless anti-Hermitian matrices."""
    operators = _operators(source, size, antihermitian_traceless(source, size))
    return generated_by(operators, name=f"su({size},{source.name})")


def sl(size: int, source: Algebra) -> LieAlgebra:
    """Return the Lie algebra generated by all traceless matrices.

    The generators are the traceless Hermitian and anti-Hermitian matrices.
    """
    matrices = (
        *antihermitian_traceless(source, size),
        *hermitian_traceless(source, size),
    )
    return generated_by(
        _operators(source, size, matrices), name=f"sl({size},{source.name})"
    )


def multiplication_algebra(
    source: Algebra, *, left: bool = True, right: bool = False
) -> LieAlgebra:
    """Return the Lie algebra generated by multiplications by imaginary elements.

    With ``left`` alone this is the 1-by-1 case ``su(1, A)``: the maps
    ``x -> a x``.  With ``right`` the maps ``x -> x a`` are included.  For
    the octonions the left multiplications already generate ``so(8)``.
    """
    if not (left or right):
        raise EasyError("shape", "choose left or right multiplications, or both")
    imaginary = [x for x in source.basis if x != source.unit]
    operators: list[Operator] = []
    for a in imaginary:
        if left:
            columns = [(a * x).vector for x in source.basis]
            operators.append(tuple(zip(*columns, strict=True)))
        if right:
            columns = [(x * a).vector for x in source.basis]
            operators.append(tuple(zip(*columns, strict=True)))
    if not operators:
        raise EasyError("shape", f"{source.name} has no imaginary elements")
    sides = "L" if not right else ("R" if not left else "LR")
    return generated_by(operators, name=f"mult_{sides}({source.name})")


def so(size: int, source: Algebra) -> LieAlgebra:
    """Return ``so(n, A)``: the antisymmetric matrices over a commutative algebra.

    Antisymmetry uses the plain transpose, so the matrices close under the
    commutator only when ``A`` is commutative and associative; any other
    algebra is rejected.  ``so(n, C)`` has real dimension ``n(n-1)``.
    """
    if size < 2:
        raise EasyError("shape", "the matrices must be at least 2-by-2")
    if not (ca.is_commutative(source) and ca.is_associative(source)):
        raise EasyError(
            "unsupported",
            f"so(n, A) needs a commutative associative algebra, not {source.name}",
        )
    generators = [
        am.unit(source, size, i, j, element) - am.unit(source, size, j, i, element)
        for i in range(size)
        for j in range(i + 1, size)
        for element in source.basis
    ]
    return generated_by(
        [column_action(matrix) for matrix in generators],
        name=f"so({size},{source.name})",
    )


# --- large cases: an exact lower bound and a modular closure check -----------


@dataclass(frozen=True)
class DimensionCertificate:
    """What a modular closure run establishes about a generated Lie algebra.

    ``independent`` commutators were found that are linearly independent
    modulo ``prime``.  Independence modulo a prime implies independence over
    the rationals, so the dimension is at least ``independent``, exactly.
    The run ends only when every commutator of those elements lies in their
    span modulo the prime, which supports, but does not prove, equality.
    """

    name: str
    prime: int
    independent: int


def dimension_certificate(
    size: int, source: Algebra, *, kind: str = "su", prime: int = 2_147_483_629
) -> DimensionCertificate:
    """Run the Lie closure of ``su`` or ``sl`` generators modulo a prime."""
    if kind not in ("su", "sl"):
        raise EasyError("unsupported", "kind must be 'su' or 'sl'")
    matrices: tuple[am.Mat, ...] = antihermitian_traceless(source, size)
    if kind == "sl":
        matrices += hermitian_traceless(source, size)
    operators = _operators(source, size, matrices)
    scale = 1
    for operator in operators:
        for row in operator:
            for value in row:
                scale = scale * value.denominator // _gcd(scale, value.denominator)
    reduced = [
        [[int(value * scale) % prime for value in row] for row in operator]
        for operator in operators
    ]
    width = len(reduced[0])
    pivots: dict[int, list[int]] = {}

    def insert(matrix: list[list[int]]) -> bool:
        vector = [value for row in matrix for value in row]
        for pivot, row in pivots.items():
            factor = vector[pivot]
            if factor:
                vector = [
                    (a - factor * b) % prime for a, b in zip(vector, row, strict=True)
                ]
        lead = next((index for index, value in enumerate(vector) if value), None)
        if lead is None:
            return False
        inverse = pow(vector[lead], -1, prime)
        pivots[lead] = [value * inverse % prime for value in vector]
        return True

    def bracket(a: list[list[int]], b: list[list[int]]) -> list[list[int]]:
        columns_b = list(zip(*b, strict=True))
        columns_a = list(zip(*a, strict=True))
        return [
            [
                (
                    sum(x * y for x, y in zip(a[i], columns_b[j], strict=True))
                    - sum(x * y for x, y in zip(b[i], columns_a[j], strict=True))
                )
                % prime
                for j in range(width)
            ]
            for i in range(width)
        ]

    basis: list[list[list[int]]] = []
    queue = list(reduced)
    while queue:
        candidate = queue.pop(0)
        if insert(candidate):
            queue.extend(bracket(candidate, other) for other in basis)
            basis.append(candidate)
    return DimensionCertificate(f"{kind}({size},{source.name})", prime, len(basis))


def _gcd(a: int, b: int) -> int:
    while b:
        a, b = b, a % b
    return a
